import { Geist } from "next/font/google";
import Link from "next/link";
import "./styles/global.scss";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./contexts/themecontext"; // Path alias

const geist = Geist({
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <script src="http://localhost:3000"></script>
      </head>
      <body>
        <header>
          <ul className="avatar">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard">Dashboard</Link>
            </li>
            <li>
              <Link href="/blog/what a slug/again another one">Blog</Link>
            </li>
            <li>
              <Link href="/products">Products</Link>
            </li>
            <li>
              <Link href="/tasks">Tasks</Link>
            </li>
            <li>
              <Link href="/headings">Headings</Link>
            </li>
          </ul>
        </header>
        <main>
          <h3>Main Starting Point</h3>
          <ThemeProvider>{children}</ThemeProvider>
        </main>
      </body>
    </html>
  );
}
